// Package token provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package token

// RoleTokenRequestBody defines model for RoleTokenRequestBody.
type RoleTokenRequestBody struct {
	// Domain Role token domain name
	Domain string `json:"domain"`

	// MaxExpiry Role token maximum expiry time (in second)
	MaxExpiry *int `json:"max_expiry,omitempty"`

	// MinExpiry Role token minimum expiry time (in second)
	MinExpiry *int `json:"min_expiry,omitempty"`

	// ProxyForPrincipal Role token proxyForPrincipal name
	ProxyForPrincipal *string `json:"proxy_for_principal,omitempty"`

	// Role Role token role name (comma separated list)
	Role string `json:"role"`
}

// RoleTokenResponse defines model for RoleTokenResponse.
type RoleTokenResponse struct {
	// ExpiryTime Role token expiry time (Unix timestamp in second)
	ExpiryTime int64 `json:"expiryTime"`

	// Token Role token string
	Token string `json:"token"`
}

// RtResponse defines model for rtResponse.
type RtResponse = RoleTokenResponse

// RtRequestBody defines model for rtRequestBody.
type RtRequestBody = RoleTokenRequestBody

// GetRoleTokenJSONRequestBody defines body for GetRoleToken for application/json ContentType.
type GetRoleTokenJSONRequestBody = RoleTokenRequestBody
